# This chapter by MeltedIce and mixed by minqwq
import os
import sys
import pygame
pygame.mixer.init()
print("没想好用什么音乐。")
print("幻想乡，山对面树林里某间屋子 | 2017-XX-XX")
input("")
print("唔~起床了")
input("")
print("今天是去新学校报道的第一天，我可不能迟到。")
input("")
print("来到教室，这里熙熙攘攘的，坐满了新同学")
input("")
print("我用着视线瞟着新同学们")
input("")
print("突然，我的视线落在一个女孩身上。")
input("")
print("<???> ......")
input("")
print("这不是昨天的那个女生吗？")
input("")
print("<minqwq> ...hi?")
input("")
print("我向她打了个招呼")
input("")
print("<???> ....你好")
input("")
print("她略带羞涩地回应了我")
input("")
print("依然是这个甜美的声音")
input("")
print("<minqwq> 我去，好巧啊，你也开始在这上学了？")
input("")
print("<???> ...是。")
input("")
print("<minqwq> 那，你叫什么")
input("")
print("<Yukari> ...我...我的名字是Yukari...")
input("")
print("她的脸染上了红晕，扭捏着")
input("")
print("<minqwq> 很高兴认识你！我的名字是minqwq，平常直接叫我min就行。")
input("")
print("")
