# This chapter by MeltedIce and mixed by minqwq
import os
import sys
import pygame
import time
import tqdm
pygame.mixer.init()
se_bell = pygame.mixer.Sound("./se/bell.mp3")
se_boom = pygame.mixer.Sound("./se/boom.mp3")
se_school_bell = pygame.mixer.Sound("./se/school_bell.mp3")
pygame.mixer.music.load("./music/Bored_House_--_minqwq.mp3")
print("音乐:Bored House | by minqwq")
pygame.mixer.music.play()
print("幻想乡，山对面树林里某间屋子 | 2017-04-09")
input("")
se_bell.play()
print("唔~起床了")
input("")
print("今天是去新学校报道的第一天，我可不能迟到。")
input("")
print("(出门前的神秘准备工作)")
input("")
print("(离开)")
print("\n幻想乡，727号公路 | 2017-04-09")
pygame.mixer.music.load("./music/runningman.mp3")
pygame.mixer.music.play(loops = -1)
print("少女走路中...(按下 Enter 键以前进。)")
for uwu0 in tqdm.tqdm(range(20)):
    input("")
print("为防止剧本展示过快，请缓慢的再按 3 次 Enter 键以继续。")
for uwu1 in range(3):
    input("")
pygame.mixer.music.load("./music/Road_727_--_minqwq.mp3")
print("音乐:Road 727 | by minqwq")
pygame.mixer.music.play()
print("来到教室，这里熙熙攘攘的，坐满了新同学")
input("")
print("我用着视线瞟着新同学们")
input("")
pygame.mixer.music.pause()
se_bell.play()
print("突然，我的视线落在一个女孩身上。")
input("")
print("<???> ......")
input("")
se_boom.play()
print("这不是昨天的那个女生吗？")
input("")
print("<minqwq> ...hi?")
input("")
print("我向她打了个招呼")
input("")
pygame.mixer.music.unpause()
print("<???> ....你好")
input("")
print("她略带羞涩地回应了我")
input("")
print("依然是这个甜美的声音")
input("")
print("<minqwq> 我去，好巧啊，你也开始在这上学了？")
input("")
print("<???> ...是。")
input("")
print("<minqwq> 那，你叫什么")
input("")
print("<Yukari> ...我...我的名字是Yukari...")
input("")
print("她的脸染上了红晕，扭捏着")
input("")
print("<minqwq> 很高兴认识你！我的名字是minqwq，平常直接叫我min就行。")
input("")
se_school_bell.play()
print("随后，上课铃响起了。")
input("")
print("我们俩随后立即摆正坐姿")
input("")
print("少女上课中...")
for uwu2 in tqdm.tqdm(range(45)):
    time.sleep(0.05)
pygame.mixer.music.load("./music/Night_of_code_--_minqwq.mp3")
print("音乐:Night of code | by minqwq")
pygame.mixer.music.play()
print("转眼见外面的太阳都快要落下去了。")
input("")
print("<minqwq> 再见")
input("")
print("<Yukari> 再见~！")
input("")
print("我们俩就这么告了别，随后我打算去咖啡厅喝杯咖啡")
input("")
print("(出门)")
input("")
print("<minqwq> 虽然走夜路很害怕，但是还是想要去喝一杯咖啡再回家啊...")
input("")
print("于是我还是打算去来一杯咖啡。")
input("")
print("少女黑夜行走中...")
for uwu3 in tqdm.tqdm(range(60)):
    time.sleep(0.1)
print("<minqwq> 终于到地方了...")
input("")
print("(推门)")
input("")
pygame.mixer.music.pause()
print("<minqwq> 老板...?")
input("")
print("<Safari> min...?")
input("")
pygame.mixer.music.unpause()
print("<minqwq> 你怎么穷的都来打工了(")
input("")
print("<Safari> 不是啦，其实就是想整点小钱买台手机而已")
input("")
print("<minqwq> 所以")
input("")
print("<minqwq> 来一杯多糖咖啡")
input("")
print("<Safari> 好")
print("福瑞制咖啡中...")
for uwu4 in tqdm.tqdm(range(800)):
    time.sleep(0.01)
print("<Safari> 好了")
input("")
print("(拿)")
input("")
print("<双方> (微笑")
input("")
print("(闻)")
input("")
print("<minqwq> 不赖啊")
input("")
print("<Safari> 那肯定，上一任老板亲自教我的")
input("")
print("(坐在店铺的某个角落里开始饮用)")
print("少女饮咖中...")
for uwu5 in tqdm.tqdm(range(680)):
    time.sleep(0.01)
print("<minqwq> 那我先走了，明天虽然不上学但是有代码没写")
input("")
print("<Safari> 好~")
input("")
print("现在处于 Another View 状态")
print("<Safari> 又无聊了...")
input("")
print("现在处于 Player View 状态")
for uwu6 in tqdm.tqdm(range(520)):
    time.sleep(0.01)
print("<minqwq> ...累死了。")
input("")
print("<minqwq> 可算到家了")
input("")
print("(飞上床)")
input("")
print("<minqwq> (闭眼)")
pygame.mixer.music.stop()
os.system("python3 ./chapter/1/3/index.py")
