# Chapter 1-1 by minqwq
import pygame
import os
import sys
pygame.mixer.init()
pygame.mixer.music.load("./music/False_Strawberry_Memories_remix__--_minqwq.mp3")
pygame.mixer.music.play()
print("幻想乡，某座山上 | 2017-04-08")
input("") # 这个东西表示"按下enter键显示下一句" | minqwq | 2024-09-12
print("<???> 抱歉----麻烦能打扰一下吗？")
input("")
print("我听到一个可爱的声音叫住了我。")
input("")
print("<???> 厕...厕所在哪里？")
input("")
print("<minqwq> 这条路前面有个分岔路口，你左转应该就能看到了。")
input("")
print("<???> (快速离开)")
input("")
print("这座山是我们这为数不多的景点")
input("")
print("但是风景非常优美")
input("")
print("常常会吸引许多人来此地旅游")
input("")
print("<???> 抱歉，我还是没找到，能带我去吗？")
input("")
print("<minqwq> ...好吧。")
input("")
print("第一次被一个女生这样跟着，我的心嘭嘭直跳。")
input("")
print("<minqwq> 好了，就是这里")
input("")
print("<???> 谢谢~")
input("")
print("她走进了厕所。")
input("")
print("回家的路上，我仍然忘不了这如此甜美的声音")
pygame.mixer.music.stop()
os.system("python3 ./chapter/1/2/index.py")
